# Test Dockerfile - standalone test with RPM postgres
FROM almalinux:9

RUN dnf install -y tar gzip xz

# Versions
ENV POSTGRES_VERSION=14.19.0
ENV FDW_VERSION=2.1.4

# Steampipe env
ENV HOME=/home/builder
ENV STEAMPIPE_INSTALL_DIR=/home/builder/.steampipe
ENV STEAMPIPE_UPDATE_CHECK=false
ENV STEAMPIPE_TELEMETRY=none

RUN useradd -m builder
WORKDIR /home/builder

# 1. Install PostgreSQL 14 from local RPMs
COPY binaries/postgresql14-libs.rpm /tmp/
COPY binaries/postgresql14.rpm /tmp/
COPY binaries/postgresql14-server.rpm /tmp/

RUN dnf install -y /tmp/postgresql14-libs.rpm /tmp/postgresql14.rpm /tmp/postgresql14-server.rpm \
    && rm /tmp/postgresql14*.rpm

# 2. Install FDW Extension into RPM postgres
COPY binaries/steampipe_postgres_fdw.so.gz /tmp/
COPY binaries/steampipe_postgres_fdw.control /tmp/
COPY binaries/steampipe_postgres_fdw--1.0.sql /tmp/

RUN gunzip -c /tmp/steampipe_postgres_fdw.so.gz > /usr/pgsql-14/lib/steampipe_postgres_fdw.so \
    && cp /tmp/steampipe_postgres_fdw.control /usr/pgsql-14/share/extension/ \
    && cp /tmp/steampipe_postgres_fdw--1.0.sql /usr/pgsql-14/share/extension/ \
    && rm /tmp/steampipe_postgres_fdw.* \
    && chown -R builder:builder /usr/pgsql-14

# 3. Steampipe CLI
COPY binaries/steampipe_linux_amd64.tar.gz /tmp/
RUN tar -xzf /tmp/steampipe_linux_amd64.tar.gz -C /usr/local/bin \
    && rm /tmp/steampipe_linux_amd64.tar.gz

# 4. Copy RPM postgres to steampipe expected location
# (In WSL, this will be a bind mount instead - see /etc/fstab)
RUN mkdir -p /home/builder/.steampipe/db/14.19.0/postgres \
    && cp -a /usr/pgsql-14/bin /home/builder/.steampipe/db/14.19.0/postgres/ \
    && cp -a /usr/pgsql-14/lib /home/builder/.steampipe/db/14.19.0/postgres/ \
    && cp -a /usr/pgsql-14/share /home/builder/.steampipe/db/14.19.0/postgres/

# 5. Database versions.json with correct digest
RUN echo '{"db":{"name":"embeddedDB","version":"14.19.0","image_digest":"sha256:84264ef41853178707bccb091f5450c22e835f8a98f9961592c75690321093d9","install_date":"2025-01-26T00:00:00Z"},"fdw_extension":{"name":"fdwExtension","version":"2.1.4","install_date":"2025-01-26T00:00:00Z"}}' \
    > /home/builder/.steampipe/db/versions.json

# 6. Install plugins from local files
COPY binaries/steampipe-plugin-jira.tar.gz /tmp/
COPY binaries/steampipe-plugin-gitlab.tar.gz /tmp/

# Jira plugin
RUN mkdir -p /tmp/jira-plugin \
    && tar -xzf /tmp/steampipe-plugin-jira.tar.gz -C /tmp/jira-plugin \
    && mkdir -p /home/builder/.steampipe/plugins/hub.steampipe.io/plugins/turbot/jira@latest \
    && gunzip -c /tmp/jira-plugin/steampipe-plugin-jira_linux_amd64.gz \
       > /home/builder/.steampipe/plugins/hub.steampipe.io/plugins/turbot/jira@latest/steampipe-plugin-jira.plugin \
    && chmod +x /home/builder/.steampipe/plugins/hub.steampipe.io/plugins/turbot/jira@latest/steampipe-plugin-jira.plugin \
    && mkdir -p /home/builder/.steampipe/config \
    && cp /tmp/jira-plugin/config/* /home/builder/.steampipe/config/ \
    && rm -rf /tmp/jira-plugin /tmp/steampipe-plugin-jira.tar.gz

# GitLab plugin
RUN mkdir -p /tmp/gitlab-plugin \
    && tar -xzf /tmp/steampipe-plugin-gitlab.tar.gz -C /tmp/gitlab-plugin \
    && mkdir -p /home/builder/.steampipe/plugins/hub.steampipe.io/plugins/theapsgroup/gitlab@latest \
    && gunzip -c /tmp/gitlab-plugin/steampipe-plugin-gitlab_linux_amd64.gz \
       > /home/builder/.steampipe/plugins/hub.steampipe.io/plugins/theapsgroup/gitlab@latest/steampipe-plugin-gitlab.plugin \
    && chmod +x /home/builder/.steampipe/plugins/hub.steampipe.io/plugins/theapsgroup/gitlab@latest/steampipe-plugin-gitlab.plugin \
    && cp /tmp/gitlab-plugin/config/* /home/builder/.steampipe/config/ \
    && rm -rf /tmp/gitlab-plugin /tmp/steampipe-plugin-gitlab.tar.gz

RUN chown -R builder:builder /home/builder/.steampipe

USER builder

# Verify symlinks (don't run steampipe commands - they download embedded postgres)
RUN ls -la ~/.steampipe/db/14.19.0/postgres/
RUN ls -la ~/.steampipe/plugins/

CMD ["steampipe", "service", "start", "--foreground"]
